### ISSUE TITLE
Saving state between screens

### ISSUE THREAD

**Issue by nathanielwolf** [square/flow#11]
How is it possible to save a state between screens when moving forward and backward in the flow?
For example, how do we maintain the list scroll position if we scroll down the conversation list in the sample code, click an item to show a conversation, and then navigate back.

**Comment by RomainPiel** [comment]
@rjrjr I'm curious to know what's the best way to keep the state in that situation. What is the sample you are talking about? I can't find anything like that.

**Comment by markymark1988** [comment]
@RomainPiel It looks like @rjrjr is talking about https://github.com/square/mortar/blob/master/mortar-hellodagger2/src/main/java/com/example/hellodagger2/Main.java
using onSave() and onLoad(). That doesn't really answer the question for me though since onSave() is not is not called when navigating the flow stack as @chrisjenx mentioned.

**Comment by Lakedaemon** [comment]
@RomainPiel I have had some success by adding (and maintaining uptodate the state of) some mutable variables to my path objects.
The StateParceler (a GsonParceler in te sample) is used when navigating screen to save/restore those objects, including those mutable variables (IF Gson is able to handle it out of te box... beware of generics and interfaces...)

**Comment by markymark1988** [comment]
@Lakedaemon do you have an example of what you are doing to solve this?

**Comment by Lakedaemon** [comment]
I code in kotlin, but in java, I guess that you would do : 

class MyScreen extends Path {
 public String myMutableState;
public MyScreen(String myInitialMutableState) {
   this.myMutableState = myInitialMutableState;
} 
}

now, you can call 

Flow.get(this).set(MyScreen("ahah"))

and in your MyScreen presenter, you can do 

    override void onLoad(Bundle savedInstanceState) {
        super.onLoad(savedInstanceState);
.....
        String myMutableState = Path.get<MyScreen>(view.getContext()).myMutableState; 
        ...
//update stuff with the value of myMutableState
    }


and if you change later on the value of myMutableState, you update it in your presenter like this
Path.get<MyScreen>(view.getContext()).myMutableState = "myBrandNewValue";

**Comment by markymark1988** [comment]
Thanks a lot for your example, @Lakedaemon. I think I'll do something similar for now.

**Comment by Zhuinden** [comment]
This is somewhat ridiculous, the `onLoad/onSave()` methods of the `ViewPresenter<T>` should be used to put the state of the presenter into the History.
