### ISSUE TITLE
A possibility to use Parcelable screens and get rid of the StateParceler?

### ISSUE THREAD

**Issue by adelnizamutdinov** [square/flow#115]
Right now we use POJOs to represent screens, and then some kind of binary/text serialization to wrap a `History` into a `Parcelable`

What about making `History` Parcelable-aware, thus eliminating an extra serialization/deserialization overhead and getting rid `StateParceler` interface?

For example `top()` would be parametrized like this:

```java
 public <T extends Parcelable> T top() {
  //noinspection unchecked
  return (T) peek(0);
}
```

**Comment by Zhuinden** [comment]
Just today I wrote this wonderful StateParceler.


    import android.os.Parcelable;

    import flow.StateParceler;

    /**
     * Created by Owner on 2015.12.29.
     */
    public class ParcelableParceler
            implements StateParceler {
        @Override
        public Parcelable wrap(Object instance) {
            return (Parcelable) instance;
        }

        @Override
        public Object unwrap(Parcelable parcelable) {
            return parcelable;
        }
    }

**Comment by adelnizamutdinov** [comment]
ha, thank you very much :)
