### ISSUE TITLE
Question - Using Activities in ServicesFactory?

### ISSUE THREAD

**Issue by donaldlittlepie** [square/flow#146]
I was looking at the new key sample and there is a comment in FlowServices about keeping it lean and using Dagger/Mortar. 

I decided to give it a shot by creating a ServicesFactory with had a reference to the main activity. I installed Flow in the activity using the same process as the sample. I used the Key to determine the Mortar scope and bind it as a service. I exposed an 'onDestroy' method which set the referenced activity to null to clean up the activity when it when the activity was being destroyed.

Long story short, when I rotated the screen and then tried to navigate to a new screen using Flow, my ServicesFactory blew up because the activity which referenced it was now null.  I assumed that when the activity was destroyed, when the new Activity was created Flow would be installed again and all would be good.  Peeking into the code the InternalLifecycleIntegration is a Fragment with the retain instance state set to true.  Most of the members are set the first time the Fragment is created with the dispatcher being the odd man out.  

The problem seemed to be that an initial instance of the Flow object was created, and had my ServiceFactory set in it's KeyManager. I rotated the device which killed the ref to the activity and tried to Flow.get().set(NewScreen()). Even though Flow was installed again when the new Activity was created, it didn't add my new ServicesFactory because the dispatcher is the only thing which set on every install, so it used the old ServicesFactory which still referenced in the Flow object which was saved by the Fragment.

Sorry for the long post, I can push a repo with the issue if you think it helps. Thanks!

**Comment by loganj** [comment]
Why do you need the Activity in your ServiceFactory?  Can you paste just your factory?

**Comment by donaldlittlepie** [comment]
class FlowServices(private var context: Context?) : ServicesFactory() {

    override fun bindServices(services: Services.Binder) {
        val key = services.getKey<Any>() as ComponentFactory<Any>;

        val parentScope = MortarScope.getScope(context)
        if (!parentScope.hasService(key.javaClass.simpleName)) {

            val component = key.createComponent(parentScope.getService(ContextServices.DAGGER_SERVICE))

            val mortarScope = parentScope.buildChild()
                    .withService(ContextServices.DAGGER_SERVICE, component)
                    .build(key.javaClass.simpleName)

            services.bind(ContextServices.DAGGER_SERVICE,
                    mortarScope.getService(ContextServices.DAGGER_SERVICE))
        }
    }

    override fun tearDownServices(services: Services) {
        val key = services.getKey<Any>();
        val serviceName = key.javaClass.simpleName
        Timber.d("Tearing down flow service %s", serviceName)

        val parentScope = MortarScope.getScope(context)
        val screenScope = parentScope.findChild(key.javaClass.simpleName)
        if (screenScope != null) {
            Timber.d("Found screen scope %s. Destroying", screenScope)
            screenScope.destroy()
        }

        super.tearDownServices(services)
    }

    fun onDestroy() {
        this.context = null
    }
}

**Comment by loganj** [comment]
I see, so `context` is your Activity?  Do you actually have a Mortar scope there, or is it just coming from the Application via the Activity?

**Comment by donaldlittlepie** [comment]
Yep `context` is the activity.  The Mortar scope is coming from the Application via the Activity.

**Comment by loganj** [comment]
It looks like you don't actually need to keep a reference to the Activity. Just get the MortarScope and keep that instead?

**Comment by donaldlittlepie** [comment]
Ah. That makes sense.  I didn't think to really look at what `MortarScope.getScope()` was doing.  I'll give that a try. Thanks for the help.

**Comment by loganj** [comment]
Thanks for raising this as an issue. I'll be sure to at least put a note in the javadoc for ServiceFactory.

**Comment by Kritarie** [comment]
@donaldlittlepie How are you retrieving your root MortarScope in Application from your Activity during attachBaseContext? The only way I can see is to retrieve it statically (which I'm not a big fan of), since the Activity context is null until super.attachBaseContext.

**Comment by donaldlittlepie** [comment]
@Kritarie Yep. That is what I did.
