### ISSUE TITLE
Long running operations

### ISSUE THREAD

**Issue by IlyaEremin** [square/flow#168]
Hello!
First of all thank you for such great library.
I just started to playing with it and my number one question: how can I perform long running operation: network etc. I don't want to do it in any `View` subclass. Your suggestions? Or maybe even example project!

**Comment by Zhuinden** [comment]
[Not a Flow dev]

Well, even in an Activity, you typically wouldn't do it in the Activity itself. You would move it to an external class, then inject that into your Activity (or maybe [Presenter, if you truly want to get rid of your Activity shackles](https://github.com/konmik/testable-activity-example/blob/master/app/src/main/java/info/android15/testableactivity/MainActivityController.java)). That external class would possibly execute the asynchronous logic in an `Executors` threadpool, and you could receive the result with EventBus.

(People are probably going to say RxJava pretty soon)

**Comment by loganj** [comment]
Thanks, but this isn't really a Flow question. I'd suggest StackOverflow for advice on long-running tasks on Android.

**Comment by IlyaEremin** [comment]
Thanks for clarification.
I just started to think about it only when started to use flow. 
You are right that this is very common question.
