### ISSUE TITLE
Add Up/Down transition Direction to Flow

### ISSUE THREAD

**Issue by markymark1988** [square/flow#170]
We are using Flow/Mortar and have a requirement to have an up/down transition when opening/returning to a certain screen. 
Currently Flow only supports FORWARD, BACKWARD, and REPLACE.

Can you please add up/down enums to Flow or allow us to extend the behavior?
Extending the behavior would be a risk we would be taking upon ourselves if the API is in rapid development.

Since it is final it looks like my current option is to fork the code and add these transitions myself to our SimplePathContainer.

Thank you

**Comment by loganj** [comment]
What do "up" and "down" mean in the context of a history?

**Comment by markymark1988** [comment]
Ah, I did not look closely at Flow's set() and goBack() methods before posting.
I think the only way I could make this work is if I'd modify the history stack to keep track of the transition direction that was used to place it on the stack. Then I would just perform the reverse transition direction when it is popped.

Is this something you would advise against or perhaps provide any suggestions if I implement this myself? 

My desired scenario is:
Open new screen that slides in from the bottom and pushes the current screen out toward the top (up). Then when I goBack() it would do the reverse.. (down)

**Comment by loganj** [comment]
So, a little secret: I rarely use Direction to choose an animation.  Instead, I look at the two keys and decide how they're related. Usually that's just inspecting metadata on the keys ("does the incoming key represent a dialog? a sheet? a drawer?  what about the outgoing key?") but sometimes it's checking both actual keys against a lookup table ("given an outgoing HomeScreen and incoming ProfileScreen, how should I animate?").  Most often it's a combination, figuring out which "kind" of screen each key represents and then looking up the animation for those kinds:  "incoming dialog, outgoing content == fade in the dialog" or "incoming dialog, outgoing dialog == crossfade the dialogs").

Very tempted to eliminate Direction entirely, but it is sometimes a useful, simple hint about the history change that's occurring.

**Comment by markymark1988** [comment]
I see. Do you have example code of how you are doing this?

Currently we are using this as our example to do the animation which does use Direction: https://github.com/square/mortar/blob/master/mortar-sample/src/main/java/com/example/mortar/screen/SimplePathContainer.java

It seems that you're saying Items from TraversalState are what I need to compare.

**Comment by markymark1988** [comment]
Thanks for your suggestions, @loganj. I ended up using a sort of lookup table. That is, since we only use screens throughout our project I have a static list of full class names for any screens that are to be considered dialogs.. Each screen that is a dialog will register/add itself to this list. 
I then use this information to determine the transition.

Since each class registers itself I won't violate the OCP.

I didn't see much else in the metadata that I could use. 
Another thought I had was to use some kind of interface that each, full-screen, screen would implement if it is considered a dialog.

**Comment by loganj** [comment]
> Another thought I had was to use some kind of interface that each, full-screen, screen would implement if it is considered a dialog.

Yep. I [use annotations for this](https://twitter.com/yashvprabhu/status/637360058762924032), but there are lots of ways to do it.

**Comment by markymark1988** [comment]
Ah, great! Much less code by using annotations.

**Comment by loganj** [comment]
Sounds like you're all set, so I'm going to close this issue. We'll look more closely at Direction as part of a larger review before beta.

**Comment by markymark1988** [comment]
:+1:
