### ISSUE TITLE
ViewState is not implicitly saved in onSaveInstanceState(), and there is no hook to Flow to trigger a state save

### ISSUE THREAD

**Issue by Zhuinden** [square/flow#174]
In `onSaveInstanceState()`, a Flow Dispatch is not triggered, and as a result, the views' state is not preserved into the `State` objects, but `onResume()` triggers a `REPLACE` direction that would destroy the previous view along with its view state.

I personally added a package-internal class that manually places the view state into the `InternalLifecycleIntegration`'s `KeyManager`, but it is not a canonical solution.

    public class ForceBundler {
        public static void saveToBundle(Activity activity, View... activeViews) {
            InternalLifecycleIntegration internalLifeCycleIntegration = InternalLifecycleIntegration.find(activity);
            if(internalLifeCycleIntegration != null) {
                KeyManager keyManager = internalLifeCycleIntegration.keyManager;
                for(View view : activeViews) {
                    State state = keyManager.getState(Flow.getKey(view));
                    state.save(view);
                    if(view instanceof Bundleable) {
                        state.setBundle(((Bundleable) view).toBundle());
                    }
                }
            }
        }
    }

Which I call in `onSaveInstanceState()`

    @Override
    protected void onSaveInstanceState(Bundle outState) {
        ForceBundler.saveToBundle(this, root.getChildAt(0));
        super.onSaveInstanceState(outState);
    }

Personally I would expect a call to the `changeKey()` method in `onSaveInstanceState()` as that triggers state persistence, and this to be managed automatically through the `KeyChanger`.

**Comment by edenman** [comment]
Here's where BasicDispatcher does it in the sample: https://github.com/square/flow/blob/master/flow-sample-basic/src/main/java/flow/sample/basic/BasicDispatcher.java#L46

This behavior should probably just be added to `KeyDispatcher`

**Comment by Zhuinden** [comment]
@edenman that's wonderful, but it doesn't run on device rotation.

**Comment by edenman** [comment]
@Zhuinden I just tested out rotation, seems to call save/restore on the screen view just fine...did you remember to set ids on all of your layout files?

**Comment by Zhuinden** [comment]
@edenman ...seriously, I seem to have forgotten to add an `android:id="@+id/custom_view"` to my custom viewgroups. With that added, view state is persisted properly. Now I kinda feel like an idiot.

However, that doesn't change the fact that in order to save your state to a **bundle** instead of a `BaseSavedState` using `View.onSaveInstanceState()`, you'll have to access the `State` directly from the `KeyManager`.

Well at least now the custom view can handle it instead of the container in `onSaveInstanceState()`, and I don't have to worry about hacking the view state in myself, so that's neat.

**Comment by loganj** [comment]
I'm a little confused. @Zhuinden can you describe in high-level terms what you expect to happen that isn't happening?

**Comment by loganj** [comment]
Are you trying to force a state save?  If so, why?

**Comment by Zhuinden** [comment]
@loganj the `KeyDispatcher` provides the `State` objects for the given context from the KeyManager and allows persistence to the `State`'s `Bundle` parameter, however, the custom view itself has no means of persisting to the `State`'s `Bundle` on its own. I personally [did that here](https://github.com/Zhuinden/First-Flow-Alpha-Project/blob/master/app/src/main/java/com/zhuinden/flow_alpha_project/MainActivity.java#L150).

So there isn't really a simple way of saving to the `State`'s `Bundle` directly for the given `Context` in `onSaveInstanceState()` from the custom view.

**Comment by loganj** [comment]
I see. The Bundle wasn't really intended for use by the view, but by the dispatcher. The use case motivating it was dispatchers who wanted to save non-view state alongside the view state.

Note that `State#save` uses `View#saveHierarchyState`-- your ViewGroup's children should already be persisted so long as they have IDs, there's no need to try to save them explicitly as your example does.

**Comment by Zhuinden** [comment]
@loganj even then, I'm not sure what kind of state you can truly persist that runs on traversals, but **not** on configuration change. Essentially, I still don't see how to store the current key state to the state without actively forcing it in `onSaveInstanceState()`, as traversals don't run for `onPause()`. The previous keys had the chance to store their state to the `State`, but not the current key.

**Comment by loganj** [comment]
It sounds like the root problem here is that Flow doesn't allow saving state on lifecycle events. That's true. We've been handling lifecycle events outside of Flow, but it probably makes sense for Flow to handle that case for you. Tracked as #181.

**Comment by loganj** [comment]
Continuing in #181
