### ISSUE TITLE
Implementing ServiceFactory properly

### ISSUE THREAD

**Issue by leonardo2204** [square/flow#177]
I'm trying to understand how to properly use the ServiceFactory class, but so far I came with nothing.
As provided in the [FlowServices.java](https://github.com/square/flow/blob/master/flow-sample-tree/src/main/java/flow/sample/tree/FlowServices.java)  @loganj says:

> In a real app, the conditional class matching shown here doesn't scale very far. Decompose by
> keys. Even better, keep your ServicesFactory lean and simple by using the key to build/lookup
> a Dagger graph or Mortar scope!

How do I accomplish this ?
I've came up with a [sample project](https://github.com/leonardo2204/Flow1.0.0-alphaExample) but it's a missing piece in my puzzle.4
**My doubt actually is, how can I create a Mortar Scope if I don't have any Context in the Service?**

Any help would be appreciated.

**Comment by verres630** [comment]
In old version of the Flow method setUpContext (PathContextFactory class) gives context for us. In new ServicesFactory I must pass context in constructor and save in field. ServicesFactory instance is created in attachBaseContext method and saved in Flow internals. When I rotate screen new instance of ServicesFactory is created and old instance is leaking Activity. I can't pass ApplicationContext because it is not created yet. I see two ways to solve this problem:
1. Pass context in bindServices method,
2. Give method to clear ServicesFactory.

**Comment by leonardo2204** [comment]
Yep, I know that, I tried that approach, but the problem that I face is when I'm creating a subgraph not derived from the Root (in my case, the Activity), I think I need to take another approach with Mortar in order to "drill down" the Scope.

In your case, if you are leaking the Activity, I think using a `WeakReference<Activity>` should solve your problem. Please, try it and post your results !

**Comment by donaldlittlepie** [comment]
@leonardo2204 Disclaimer: I am in now way a expert with Mortar/Flow :).  I had a similar issue as you (I think - https://github.com/square/flow/issues/146). In my case I didn't really need the "activity" mortar scope.  The activity scope didn't make sense because I only ever had a single activity, so I could manage with application and screen scoped mortar scopes.

With that said rather than giving the context to the ServiceFactory I gave the ServiceFactory the MortarScope directly. If you look at your ScreenScoper class you only need the context to fetch the parent scope.  I was able to get get the "root" the mortar scope from the application and in my services factory I created a screen scope from this parent.

**Comment by leonardo2204** [comment]
@donaldlittlepie Hmm I see what you mean... Do you have a sample of what you have done, so I can see your ScreenScoper? Actually, my doubt is, after you get the parent scope, how do you manage to "drill the scopes down" until you reach the desired context? e.g. In case of a subcomponent in dagger 2? 
Thank you so much!

**Comment by donaldlittlepie** [comment]
Here is the sample I had working - https://github.com/donaldlittlepie/buckets. The functionality is in a half baked state, but at this point I was just trying to navigate around using flow and mortar.  

The key classes https://github.com/donaldlittlepie/buckets/blob/master/app/src/main/kotlin/com/wontondon/buckets/ui/MainActivity.kt and https://github.com/donaldlittlepie/buckets/blob/master/app/src/main/kotlin/com/wontondon/buckets/ui/FlowServices.kt

One thing to note is that the MainActivity class does have some methods getMotarScope which look like it is using the Activity scope. Those aren't actually being used they were just copy/paste from the sample I was using to try and set everything up. I didn't think I would be sharing it so I didn't remove them :).

**Comment by leonardo2204** [comment]
I see what you did there... I think that I implemented it in a very alike way but I think that the same problem that I have will happen in your implementation. Try creating like a dialog, inheriting the scope from the actual key (not with the activity or app scope as root). You will get a casting exception, am I right?


Thank you again!


Enviado do Outlook Mobile






On Fri, Mar 11, 2016 at 5:05 PM -0800, "Donnie McNeal" <notifications@github.com> wrote:





Here is the sample I had working - https://github.com/donaldlittlepie/buckets. The functionality is in a half baked state, but at this point I was just trying to navigate around using flow and mortar.

The key classes https://github.com/donaldlittlepie/buckets/blob/master/app/src/main/kotlin/com/wontondon/buckets/ui/MainActivity.kt and https://github.com/donaldlittlepie/buckets/blob/master/app/src/main/kotlin/com/wontondon/buckets/ui/FlowServices.kt

One thing to note is that the MainActivity class does have some methods getMotarScope which look like it is using the Activity scope. Those aren't actually being used they were just copy/paste from the sample I was using to try and set everything up. I didn't think I would be sharing it so I didn't remove them :).

---

**Comment by loganj** [comment]
It's perfectly safe for a ServicesFactory to retain a reference to the base context which is passed to `attachBaseContext`, which should have access to the application. It's true that it's unsafe for it to keep a reference to the Activity.

I'll try to get a dagger and/or mortar sample together soon; we have an internal need for one as well.

**Comment by leonardo2204** [comment]
@loganj Sorry to bother again, any news on the Sample matter ? 
Thank you !

**Comment by pardom** [comment]
In the interest of keeping this thread alive and creating a common solution, here's what I've been using with some success:
https://gist.github.com/pardom/a403b7aae00f74ee023bfd5beaecae3e

Feedback and collaboration is encouraged, as this is somewhat in flux.

**Comment by Zhuinden** [comment]
Services don't work properly because of https://github.com/square/flow/issues/231

**Comment by loganj** [comment]
@zhuinden As you discovered, services are not meant to be exposed directly via Context. I'm comfortable with your assessment.

No longer planning a dagger/mortar sample. If we produce one internally maybe we'll publish. In the meantime @leonardo2204's looks fine to me.

**Comment by leonardo2204** [comment]
@loganj cool, thansk for the updates
