### ISSUE TITLE
Listener for Key removed?

### ISSUE THREAD

**Issue by sockeqwe** [square/flow#179]
I might have overlooked something but is there a way to get notified when a `Key` has been removed from `History` (i.e. user has pressed the back button and navigated to previous screen, or user has "rewritten" history,etc.)

If not, I think it would be useful for other third party libraries to listen for such changes (mainly Key removed) and therefore I would like to open a Feature-Request for that.

**Comment by loganj** [comment]
This can easily be done in your Dispatcher implementation. Without a specific and broadly applicable use case, I'm disinclined to add the feature.

**Comment by sockeqwe** [comment]
I know that this can be done in Dispatcher, but in my opinion it would be a cleaner and more extensible approach to implement an observing mechanism for History changes (maybe the Dispatcher could be seen as one such History Observer).

The use case I have is: Imagine a library (like an MVP library) that manages some components (like Presenters), but those components should live just as long as needed. Therefore observing the history would be useful to determine when those components are no longer needed.

**Comment by hannesstruss** [comment]
This might be a usecase for a [`flow.ServicesFactory`](https://github.com/square/flow/blob/master/flow/src/main/java/flow/ServicesFactory.java)?

**Comment by sockeqwe** [comment]
yes, but I was more hoping to find an flow independent way, so that this library could offer a "flow plugin" the user can plug in once setting up flow in Activity. Couldn't this plugin be a `ServiceFactory` one might ask? Yes, but then the user of this library still have to connect `ServiceFactory` and  and the third party library manually in his View. I was hoping to find a solution that requires writing less code for the user of the third party library and I think this could be achieved by observing the History.

**Comment by loganj** [comment]
The ServiceFactory is exactly the intended extension point.
