### ISSUE TITLE
Flow.get(this) return null in onCreate() Activity method

### ISSUE THREAD

**Issue by rovkinmax** [square/flow#184]
```Java

@Override
    protected void attachBaseContext(Context newBase) {
        newBase = Flow.configure(newBase, this)
                .defaultKey(R.id.menu_dahsboard)
                .dispatcher(new MainDispatcher(this))
                .install();
        super.attachBaseContext(newBase);
    }

    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Flow flow = Flow.get(this);
   }
```
but `flow` is null.

**Comment by Zhuinden** [comment]
Have you tried `Flow.get(getBaseContext())`?

**Comment by leonardo2204** [comment]
I couldn't understand why you are using Flow.get inside the onCreate of the Activity, usually you use it inside some view.. 
Anyway, this is not the place to post this kind of stuff, please, use StackOverflow for that kind of question !

Thanks

**Comment by Zhuinden** [comment]
@leonardo2204 it's true, the Activity context does not contain a Flow instance because it's not a InternalFlowContextWrapper.

He would be able to obtain Flow only from the view that he inflates using the incomingContexts from the KeyChanger.

**Comment by leonardo2204** [comment]
@Zhuinden  Exactly ! Anyway I don't see the point of using Flow in the activity itself `Context`

**Comment by maxandron** [comment]
There is no point of using flow there (especially with the default context), but what should be added then is an `IllegalStateException` if the Flow system service is not found.
Also the method should be annotated then as `@NonNull`

**Comment by loganj** [comment]
The exception itself wouldn't be very valuable-- usually you find out immediately that something's wrong via a NullPointerException. But it provides a hook to offer some help, in the exception message. Definitely worth considering, and if someone put together a PR with a helpful exception message I'd be inclined to accept it.  @maxandron care to take a swing?  If not let me know, I'll try to get to it soon.

**Comment by maxandron** [comment]
Consider it done!

**Comment by loganj** [comment]
#187 seems like the appropriate continuation here.
