### ISSUE TITLE
Who should be responsible for animating transitions?

### ISSUE THREAD

**Issue by mmangliers** [square/flow#186]
In a sense, I feel the dispatcher knows everything it needs to to animate the transition between two screens - it has the start and end screens as well as the direction, so we'll always know everything we need to start a transition animation.

Animating is more a job for a presenter, but the presenter doesn't know anything about the transition. Further, many screens might use the same transitions. What kind of pattern should we implement with Flow to identify a transition based on the two screens and kick it off?

**Comment by Zhuinden** [comment]
Well,  only the dispatcher can jumpstart the animation based on the traversal direction,  but when we needed different animations,  the path specified how to start the new path.  So in this case,  the key can know how to start the view bound to it.

**Comment by mmangliers** [comment]
I ended up scoping my presenters; I had a top level presenter that would examine the keys to determine the overall layout of the screen, then the keys would give that presenter the custom views to attach (which had their own presenters). It worked alright.

Ended up having to ditch Flow though; I was getting weird issues with the dispatcher getting called multiple times.
