### ISSUE TITLE
TreeKey and MultiKey shouldn't be mutually-exclusive.

### ISSUE THREAD

**Issue by fengdai** [square/flow#188]
A key should be able to implement both TreeKey and MultiKey. Because the two interfaces are not logically mutually-exclusive.

For an instance. A NormalScreen and A DialogScreen, they both have parent key CommonPath. The implementation should be like this:

``` java
public class NormalScreen implements TreeKey {
    public NormalScreen() {
    }

   @Override public Object getParentKey() {
    return new CommonPath();
   }
}
```

``` java
public class DialogScreen implements MultiKey, TreeKey {
    final Object mainContent;
    public DialogScreen(NormalScreen mainContent) {
        this.mainContent = mainContent;
    }

   @Override public List<Object> getKeys() {
       return Collections.singletonList(mainContent);
   }

   @Override public Object getParentKey() {
    return new CommonPath();
   }
}
```

**Comment by Zhuinden** [comment]
MultiKey just means it can have multiple "parents", or at least "keys that exist at the same time".

Honestly, TreeKey is just a 1-element multikey.

**Comment by fengdai** [comment]
I agree that MultiKey means "keys that exist at the same time". But I don't agree that it can have multiple "parents". Multikey's keys are not it's "patents". KeyManager#setUp method also implicites this.
And I don't think MultiKey is a general case of TreeKey. The MultiKey-sample implicites that Multikey has nothing to do with Treekey. That's why I think a key should be able to implement both.

**Comment by Zhuinden** [comment]
First of all, I'm not a Flow person, just a random guy.
Second of all, are we not reading the same code?

    if (key instanceof MultiKey) {
      for (Object part : ((MultiKey) key).getKeys()) {
        setUp(part);
      }
      ensureNode(parent, key).uses++;
    } else if (key instanceof TreeKey) {
      TreeKey treeKey = (TreeKey) key;
      final Object parentKey = treeKey.getParentKey();
      setUp(parentKey);
      parent = managedServices.get(parentKey).services;
      ensureNode(parent, key).uses++;
    //...

It's quite obvious that `TreeKey` is a special case of `MultiKey` in the sense that it has only 1 parent, but otherwise does the exact same thing as MultiKey.

**Comment by Zhuinden** [comment]
I was planning to ramble about how they are the same thing, but they really aren't. MultiKey is missing an additional step.

``` java
  void setUp(Object key) {
    Services parent = managedServices.get(ROOT_KEY).services;
    if (key instanceof MultiKey) {
      for (Object part : ((MultiKey) key).getKeys()) {
        setUp(part);
      }
      ensureNode(parent, key).uses++;
    } else if (key instanceof TreeKey) {
      TreeKey treeKey = (TreeKey) key;
      final Object parentKey = treeKey.getParentKey();
      setUp(parentKey);
      parent = managedServices.get(parentKey).services;
      ensureNode(parent, key).uses++;
    } else {
      ensureNode(parent, key).uses++;
    }
  }
```

It would be the same if Multikey called

      ensureNode(part, key).uses++;

But it doesn't. In that case, it shouldn't be `else if`, I guess.

**Comment by fengdai** [comment]
That's what I mean.

**Comment by fengdai** [comment]
@loganj Any official explanation?

**Comment by loganj** [comment]
It's confusing and introduces diamond problems.

**Comment by fengdai** [comment]
Do you mean that a DialogScreen like [flow-sample-multikey's](https://github.com/square/flow/blob/master/flow-sample-multikey/src/main/java/flow/sample/multikey/DialogScreen.java) will never have parent key? But in real world, DialogScreen isn't always as simple as a "message dialog". Sometimes a dialog can have very complex UI and depend on a variety of resources. How can we share the resources with other screens without TreeKey?

**Comment by fengdai** [comment]
@loganj Do you mean that a DialogScreen like flow-sample-multikey's will never have parent key? But in real world, DialogScreen isn't always as simple as a "message dialog". Sometimes a dialog can have very complex UI and depend on a variety of resources. How can we share the resources with other screens without TreeKey?

**Comment by Zhuinden** [comment]
If they are mutually exclusive, then how are you supposed to have a master detail flow,  where the detail has its own dialog in an additional Key app state?

**Comment by loganj** [comment]
They're not mutually exclusive, exactly. MultiKeys are meant to compose horizontally, rather than vertically.

> [MultiKey's] component keys may be ordinary objects, {@link TreeKey}s, or MultiKeys.

So maybe something like this:

```java
public class Master implements TreeKey { /* ... */ }
public class Detail implements TreeKey { /* ... */ }
public class DialogContent implements TreeKey { /* ... */ }

public class MasterDetail implements MultiKey {
  public List<Object> getKeys() {
    return Arrays.asList(master, detail);
  }
}

public class Dialog implements MultiKey {
  public List<Object> getKeys() {
    return Arrays.asList(masterDetail, dialogContent);
  }
}
```

Maybe the fact that the MultiKey is itself treated as a key, and not just a container for keys, is creating more problems than it solves.

**Comment by fengdai** [comment]
> Maybe the fact that the MultiKey is itself treated as a key, and not just a container for keys, is creating more problems than it solves.

I agree. Flow-sample-multikey module should be updated.

**Comment by loganj** [comment]
Well, that's a behavior change. If MultiKeys shouldn't be treated as keys, I'd need to make some changes in KeyManager.

**Comment by loganj** [comment]
Coming around to the notion that MultiKeys should not be treated as keys, but just as history frames that hold a list of keys. This would simplify a lot.

**Comment by dcow** [comment]
@loganj I like that notion.

**Comment by loganj** [comment]
Closing this discussion, #207 seems like the way forward here.
