### ISSUE TITLE
java.lang.IllegalArgumentException: History may not be empty

### ISSUE THREAD

**Issue by GrahamRogers** [square/flow#200]
This exception occurs when `Flow.goBack()` is called during a transition and `History.size() == 1`.

The code in `Flow.goBack()` should just return `true` if a transition is in progress otherwise the `builder.pop` call removes the last key and `setHistory` crashes with an `IllegalArgumentException`.

**Comment by osama-lionheart** [comment]
@GrahamRogers this is the same as #195

**Comment by Zhuinden** [comment]
This is because you shouldn't call super.onBackPressed during a transition

**Comment by rjrjr** [comment]
Closing as a dup of #195

**Comment by rjrjr** [comment]
See also #197
