### ISSUE TITLE
Is Flow still alive?

### ISSUE THREAD

**Issue by andrewtoth** [square/flow#203]
The last activity by a maintainer was four months ago. Is this project still alive? It is definitely a big improvement over Fragment back stack, but is it still being maintained? The lack of documentation is a huge hindrance, and is very uncharacteristic of a Square maintained OSS project.

**Comment by rjrjr** [comment]
Yes, Flow is very alive, though its main contributors frequently find themselves unable to detach from the day jobs for months at a time.

**Comment by Zhuinden** [comment]
@andrewtoth Flow is going towards 1.0.0-beta, although I personally started off a [branch of my own](https://github.com/Zhuinden/flowless) - it's still a work in progress, but I **am** using it for my projects.
