### ISSUE TITLE
InternalLifecycleIntegration.find(activity) can return null if fragment is not yet attached or is already detached 

### ISSUE THREAD

**Issue by Zhuinden** [square/flow#218]
https://github.com/square/flow/blob/master/flow/src/main/java/flow/InternalContextWrapper.java#L54

In `onCreate` of Activity or `onPostExecute` of an AsyncTask during rotation can return `null` for the fragment, resulting in not obvious NPE

**Comment by Zhuinden** [comment]
https://github.com/square/flow/issues/218

**Comment by letitfly** [comment]
I ran into this too. Time for a setAsync(key) ?

**Comment by Zhuinden** [comment]
@letitfly workaround is to call `Flow.get(getBaseContext());` in Activity.onPostCreate()

**Comment by letitfly** [comment]
thanks!

**Comment by rjrjr** [comment]
Closing this as a dup of #211. Please push back if that's a mistake.
