### ISSUE TITLE
Expose a history-filtering hook

### ISSUE THREAD

**Issue by rjrjr** [square/flow#220]
@NotPersistent doesn't scale well when you're trying to use MultiKey and TreeKey. E.g., suppose your TreeKey hierarchy has entries that look like this:

Root > LoggedIn > Senstive > ScreenFiveOfEightyInSensitiveScope

I'd like to be able to put @NotPersistent on Sensitive, but Flow won't see it there. But do we really want to invite the kind of poisoning surprises that would happen when a stray annotation is applied to a common ancestor? 

Rather than making @NotPersistent more complicated, it seems like we should drop it and instead introduce a hook to allow a delegate to filter history as its being saved. 

See also issue #216

**Comment by loganj** [comment]
Exposing a hook is the way to go. _Maybe_ we could keep an implementation based on `@NotPersistent`.

**Comment by rjrjr** [comment]
Something like this:

```interface HistoryFilter {
  History scrubHistory(History h);
}

class Flow {
  void setHistoryFilter(HistoryFilter filter);
}
```

With a default implementation that preserves the current `@NotPersistent` behavior.
