### ISSUE TITLE
`Flow.get(context)` returns null during `Activity.onCreate`

### ISSUE THREAD

**Issue by ScottPierce** [square/flow#258]
I'm configuring and installing `Flow` in `attachBaseContext`, and one of the issues that I keep running into, especially around creating objects that are tied to the Activity's lifecycle that want `Flow` in their constructor (or inject in their constructor), is that `Flow.get()` returns null / throws an error in normal parts of the `Activity` creation lifecycle.

This has bitten me several times in the past few months.

**Comment by loganj** [comment]
This is true, and not likely to change soon. It's documented as of #244. See also #211.
