### ISSUE TITLE
State not reloaded

### ISSUE THREAD

**Issue by mikepschneider** [square/flow#260]
I've configured Flow in my single-activity app according to the documentation.  The backstack works correctly and I can see via the debugger that the stack is saved out when the app is closed.

However, when I reopen the app the InternalLifecycleIntegration.load() function is never called.

In my Activity I can see that the normal onCreate, onStart, onResume lifecycle is followed.

Why would the app not reload the saved state?

**Comment by mikepschneider** [comment]
With further digging it seems that InternalLifecycleIntegration.onActivityCreated() is always called with a null bundle, thus it is unable to load.  However I clearly see that a reasonable bundle (with the right screen objects) is being created in InternalLifecycleIntegration.onSaveInstanceState() and added to the outState bundle.  But it seems like the OS just doesn't resupply the saved bundle in onActivityCreated.

Any idea why this would happen?   FYI I am using a Pixel emulator with API 25.  Also tried a Motorola Nexus 6 (not emulator) with API 24 and same results.

**Comment by Zhuinden** [comment]
Bundle will be non-null if you put the application in background with HOME, click the "terminate application" button in Android Studio, then relaunch the app from launcher. This is how you can simulate low memory condition behavior.
