### ISSUE TITLE
Flow.Callback is difficult to honor across configuration changes.

### ISSUE THREAD

**Issue by rjrjr** [square/flow#37]
The reentrance fix introduced last week requires the `Flow.Listener` to call `Flow.Callback#onComplete` after animation and such has settled down. This is a difficult contract to honor if a configuration change happens in midflight, and the sample app doesn't even try. 

OnWindowAttachListener would be a nice way to handle this without changing the ScreenSwitcher API, but it requires level 18 and we really can't abandon ICS users yet.

**Comment by loganj** [comment]
Resolved by introduction of ActivityFlowSupport.  @rjrjr feel free to reopen if I'm mistaken.
