### ISSUE TITLE
consolidate forward(Backstack) and backward(Backstack)

### ISSUE THREAD

**Issue by rjrjr** [square/flow#57]
Either replace them with a single resetTo(Backstack, Direction) method (once that name is freed up by https://github.com/square/flow/issues/55). 

But when addressing this, think hard about whether the Direction enum really is necessary at all.

**Comment by loganj** [comment]
This is on master now as `set(Backstack, Direction)`. For the moment at least, we're keeping `Direction`; it's likely here to stay.
