### ISSUE TITLE
release 0.9?

### ISSUE THREAD

**Issue by andaag** [square/flow#58]
The last commit of the "API quake" upgrade was 3 months ago, would be good to see an actual release :)

**Comment by spierce7** [comment]
I keep checking back several times a week myself.

**Comment by runningcode** [comment]
+1

**Comment by NigelHeylen** [comment]
+1

**Comment by wdawiskiba** [comment]
+1

**Comment by rjrjr** [comment]
Working on it, honest. Thanks for your patience.

**Comment by wdawiskiba** [comment]
@rjrjr can you give us an estimated release date?
I'm wondering if it's worth starting new project with 0.8, an many things are just about to change.

**Comment by rjrjr** [comment]
We will cut 0.9 by the end of the month. The last real point of debate is
whether or not to make Flow manage Objects or Paths.

**Comment by ryanzor** [comment]
+1, looking forward to 0.9

**Comment by ihal20** [comment]
+1 0.9 would be awesome!

**Comment by pardom** [comment]
+1

**Comment by rjrjr** [comment]
@loganj ...

**Comment by loganj** [comment]
Closing this issue. We're converging on a release, but I don't want to predict a date. Could be this week (since I'm off and may have time), might be later.
