### ISSUE TITLE
Backstack entry's view state is never saved on rotation

### ISSUE THREAD

**Issue by almozavr** [square/flow#67]
### Precondition
According so sample, in case of screen rotation NonConfigurationInstance is used to save backstack
### Problem
Backstack entry's `viewState` is not saved on ration, so when recreating flow with backstack, topmost entry doesn't have what to restore and views data (such as text for `EditText`) is lost.

**Comment by almozavr** [comment]
↑ Here is an example of solving issue for rotation only situation (when backstack stays the same instance).

**Comment by almozavr** [comment]
Please, could someone tell me why `ActivityFlowSupport#getBackstackToSave(Backstack backstack)` creates a copy of `backstack` with dropped `viewstates`? This is key to problem of overall persistance (e.g. activity was destroyed and user goes back to app again)

**Comment by almozavr** [comment]
↑ Fix for graceful backstack's viewstates persistance. Don't know if it's dirty for current code model, so punish hard, ready to take it further

**Comment by rjrjr** [comment]
PTAL at https://github.com/square/flow/pull/72/files

**Comment by almozavr** [comment]
@rjrjr Sorry, I found no solution of this problem in #72, because: 
- ActivityFlowSupport#getBackstackToSave still ignores current viewstates of backstack entries;
- flow support doesn't do snapshot of viewstate of current path before getBackstackToSave called, so I suppose e.g. EditText text will still be lost on rotation.

**Comment by rjrjr** [comment]
Yup, rotation is definitely broken. Still not sure that this is the way to fix it though, looking.

**Comment by loganj** [comment]
Yep. Thanks for the catch, and for the patches. I've made some slightly different fixes in #75.

**Comment by almozavr** [comment]
Thanks, looks great.
