### ISSUE TITLE
Compatibility with AppCompat v22.1.0 on API < 21

### ISSUE THREAD

**Issue by osama-lionheart** [square/flow#88]
Due to issues explained in https://github.com/square/mortar/issues/145, current version of flow crashes when updating appcompat to v22 on pre-lollipop devices.

**Comment by Lakedaemon** [comment]
Yes I'm using AppCompatActivity (to get support for the  api range 9 to 22) and I believe that I suffer from this exact issue. Thanks for the pointer.

**Comment by loganj** [comment]
resolved in newer support libraries, and I believe on master.
