### ISSUE TITLE
sample with AppCompatActivity

### ISSUE THREAD

**Issue by Lakedaemon** [square/flow#89]
As the method onRetainNonConfigurationInstance() is final in AppCompatActivity, 
1) Does flow work with AppCompat ? 
2) if yes, how should one modify the MainActivity class (in the sample) to work with AppCompatActivity ?

**Comment by almozavr** [comment]
```java
NonConfigurationInstance nonConfig;
        if (activity instanceof FragmentActivity) {
            nonConfig = (NonConfigurationInstance) ((FragmentActivity) activity).getLastCustomNonConfigurationInstance();
        } else {
            nonConfig = (NonConfigurationInstance) activity.getLastNonConfigurationInstance();
        }
```
and
```
@Override public Object onRetainCustomNonConfigurationInstance() {
        return presenta.provideNonConfigurationInstance();
    }
```

**Comment by Lakedaemon** [comment]
Thanks for the tip. I got it to work with 
@Override public Object onRetainCustomNonConfigurationInstance() {
        return flowSupport.onRetainNonConfigurationInstance()
   }

and your change in onCreate with 

     flowSupport = FlowDelegate.onCreate(nonConfig, getIntent(), savedInstanceState, parceler, History.single(....my history ...), this)
