### ISSUE TITLE
Flow sample without Flow.Path

### ISSUE THREAD

**Issue by olegosipenko** [square/flow#92]
As you divided Flow to Flow and Flow.Path it would be great to create sample application without using Path because now it's not clear why anyone should use Path and the idea behind it. Documentation in Path class on that theme is missing. Thanks

**Comment by doridori** [comment]
+1

**Comment by DmitriyZaitsev** [comment]
I've got such really simple example for Flow v0.12. Please see [FlowExample] (https://github.com/DmitriyZaitsev/FlowExample). I hope it can be helpful.

**Comment by loganj** [comment]
Writing appropriate samples now.  Path has been internalized, and there are already samples without it on master. Samples with it are coming.
