### ISSUE TITLE
dispatch is called twice on startup

### ISSUE THREAD

**Issue by andaag** [square/flow#93]
Hi

dispatch gets called twice on startup in the sample.

onResume has the following code:
if (!dispatcherSet) {
      dispatcherSet = true;
      flow.setDispatcher(dispatcher);
    }

The boolean is never set in construction, this triggers setDispatch twice.

I can submit a PR, but I'm uncertain about whether or not the boolean should be set. Or setDispatch should check if it's set to the same as it was before. (if (this.dispatch == dispatch) return;). 

Although I wouldn't neccesarly expect a callback immediately after setDispatch so a this.dispatch==dispatch check would work fine for us. I'm not sure on what other situations this might be used. I guess updating the boolean is a more safe option.

**Comment by loganj** [comment]
Fixed with changes on master. Thanks!
