### ISSUE TITLE
viewState.save is not run on rotate in sample

### ISSUE THREAD

**Issue by andaag** [square/flow#94]
Hi

The view is not detached before onSaveInstanceState, therefor viewState.save is not run.

I can't really see any clear good way to solve this either... Yes one could run that method manually, but we have a presenter like pattern where we do state saving/cleanup in onDetachedFromWindow. This function does trigger, but it triggers after serialization, which is obviously a problem. 

This worked for us in 0.8 since the objects before and after rotation were the same instance instead of being serialized/deserialized like they are in my tests now. (Which I'm a little surprised happens, but I haven't dug into why yet).

**Comment by andaag** [comment]
A little update. We have a custom StateParceler which does serialization at the wrong stage (outside the parceler instead of inside). Why this worked before I have no idea, but it should be trivial to fix.

The original issue still remains though.

**Comment by loganj** [comment]
Should be fixed with the new lifecycle integration on master, thanks!
