### ISSUE TITLE
Flow and actionBar

### ISSUE THREAD

**Issue by Lakedaemon** [square/flow#95]
In a single Activity + flow  setting  (with optionnaly mortar + dagger).
What is the prefered way/best practice to handle the actionBar/Menu ? 

delegate the onCreateOptionsMenu and onPrepareOptionsMenu methods of the activity 
and handling them depending on the current view ? 

If a flow app naviguates between CustomViews, which are UI states, aren't menu configuration supposed to be part of that state ?

**Comment by andaag** [comment]
My 2 cents : Do yourself a huge favor and use the standalone toolbar. Then things are properly seperated, and you don't need to keep something in sync when switching between views.

**Comment by Lakedaemon** [comment]
Thanks for the advice. I'll look into that.

**Comment by loganj** [comment]
We've also largely solved this by using separate instances, and not sharing actionbars at all.
