### ISSUE TITLE
Flow.get

### ISSUE THREAD

**Issue by Lakedaemon** [square/flow#96]
I would like to have a method that takes a context and returns a path (if there is one) or (null or somme other NO_PATH constant path value) if there is not. But it is quite dirty to implement with the current Flow.get method implementation : 

public static <T extends Path> T get(Context context) {
    LocalPathWrapper wrapper = LocalPathWrapper.get(context);
    if (wrapper == null) {
      throw new IllegalArgumentException("Supplied context has no Path");
    }
    // If this blows up, it's on the caller.  We hide the cast as a convenience.
    //noinspection unchecked
    return (T) wrapper.localScreen;
  }

As LocalPathWrapper is a private class, you have to use Flow.get inside a try/catch block to return null/a sentinel value...

Isn't it an usual situation to wonder where you are ? (and to want to guard against the fact that you are not insifde a flow screen ?)

**Comment by loganj** [comment]
It's really unusual to not know if you're on a Path or not.

That said, LocalPathWrapper is problematic for testing.  I've filed #139 as a broader issue to support mocking in tests.
