### ISSUE TITLE
Releases listed on GibHub aren't current

### ISSUE THREAD

**Issue by HeyLookItsBrandon** [square/flow#98]
The "releases" page on GitHub's Flow repository shows 0.8 as the most recent version but those artifacts seem to be fairly outdated.  In comparison, the most recent release mentioned in CHANGELOG.md is 0.10.  Can/should new releases be added to the repository's page on GitHub?

**Comment by lklots** [comment]
I am looking into the flow libraries myself. The lack of releases is signaling that these libraries are being abandoned. Is that true?

**Comment by balysv** [comment]
It's more likely that the last two releases were just forgotten to be tagged. `Flow 0.10` is available on maven central and was released about two months ago.

**Comment by lklots** [comment]
@balysv, ah yea, should have checked there first. i was jumping to conclusions again. sorry.

**Comment by loganj** [comment]
Added tags for 0.9 and 0.10, and we'll do better in the future. Thanks!
