### ISSUE TITLE
selectHistory prioritizes intent history over savedinstancestate

### ISSUE THREAD

**Issue by andaag** [square/flow#99]
Hi

I'm using setHistoryExtra as a way to initialize a history from for example notifications.

onCreate will correctly find the savedinstancestate history in that state, but it will be overridden by selectHistory which prioritizes the history from the intent. That seems like an odd thing? I don't see any case where I would want the intent history (which is static) to override the savedinstancestate history?

**Comment by pyricau** [comment]
:+1: this is definitely a bug.

The passed in intent is meant as a way to initially start an activity with a given history. Once we save and restore the instance state, we should not look at the intent.

**Comment by rjrjr** [comment]
Fixed by https://github.com/square/flow/pull/119
